// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// RVcoeff
arma::mat RVcoeff(arma::mat mDx, arma::mat mDy, arma::mat mC);
RcppExport SEXP _perfectphyloR_RVcoeff(SEXP mDxSEXP, SEXP mDySEXP, SEXP mCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mDx(mDxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mDy(mDySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mC(mCSEXP);
    rcpp_result_gen = Rcpp::wrap(RVcoeff(mDx, mDy, mC));
    return rcpp_result_gen;
END_RCPP
}
// dCor
arma::mat dCor(arma::mat mDx, arma::mat mDy, arma::mat mC);
RcppExport SEXP _perfectphyloR_dCor(SEXP mDxSEXP, SEXP mDySEXP, SEXP mCSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type mDx(mDxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mDy(mDySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mC(mCSEXP);
    rcpp_result_gen = Rcpp::wrap(dCor(mDx, mDy, mC));
    return rcpp_result_gen;
END_RCPP
}
// distMatRcpp
arma::mat distMatRcpp(int len, arma::vec len2, int nHaplos, arma::mat mD);
RcppExport SEXP _perfectphyloR_distMatRcpp(SEXP lenSEXP, SEXP len2SEXP, SEXP nHaplosSEXP, SEXP mDSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type len2(len2SEXP);
    Rcpp::traits::input_parameter< int >::type nHaplos(nHaplosSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mD(mDSEXP);
    rcpp_result_gen = Rcpp::wrap(distMatRcpp(len, len2, nHaplos, mD));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_perfectphyloR_RVcoeff", (DL_FUNC) &_perfectphyloR_RVcoeff, 3},
    {"_perfectphyloR_dCor", (DL_FUNC) &_perfectphyloR_dCor, 3},
    {"_perfectphyloR_distMatRcpp", (DL_FUNC) &_perfectphyloR_distMatRcpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_perfectphyloR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
