# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the RV coefficient using Rcpp
#' 
#' @param mDx A numeric matrix of pairwise distances.
#' @param mDy A second numeric matrix of pairwise distances.
#' @param mC See the equation 2.4 in Josse and Homes manual.
#' 
#' @keywords Internal
NULL

RVcoeff <- function(mDx, mDy, mC) {
    .Call(`_perfectphyloR_RVcoeff`, mDx, mDy, mC)
}

#' Compute the dCor coefficient using Rcpp
#' 
#' @param mDx A numeric matrix of pairwise distances.
#' @param mDy A second numeric matrix of pairwise distances.
#' @param mC See the equation 2.4 in Josse and Homes manual.
#' 
#' @keywords Internal
NULL

dCor <- function(mDx, mDy, mC) {
    .Call(`_perfectphyloR_dCor`, mDx, mDy, mC)
}

#' 
#' This function computes the pair wise distances of tips according to the branching order using Rcpp.
#' 
#' @param len Length of tip set 1.
#' @param len2 Length of tip set 2.
#' @param nHaplos Number of haplotypes.
#' @param mD Distance matrix
#' 
#' @keywords internal
NULL

distMatRcpp <- function(len, len2, nHaplos, mD) {
    .Call(`_perfectphyloR_distMatRcpp`, len, len2, nHaplos, mD)
}

